// The 26 letters: French name spelling, IPA, and an English sound hint.

const LETTERS = [
  { letter: 'A', name: 'a', ipa: '[ɑ]', hint: 'like "ah" in father' },
  { letter: 'B', name: 'bé', ipa: '[be]', hint: 'like "bay" (no y-glide)' },
  { letter: 'C', name: 'cé', ipa: '[se]', hint: 'like "say" (no y-glide)' },
  { letter: 'D', name: 'dé', ipa: '[de]', hint: 'like "day" (no y-glide)' },
  { letter: 'E', name: 'e', ipa: '[ə]', hint: 'like "uh" in about' },
  { letter: 'F', name: 'effe', ipa: '[ɛf]', hint: 'like "eff" in effort' },
  { letter: 'G', name: 'gé', ipa: '[ʒe]', hint: 'like "zhay" — soft g as in measure' },
  { letter: 'H', name: 'ache', ipa: '[aʃ]', hint: 'like "ash"' },
  { letter: 'I', name: 'i', ipa: '[i]', hint: 'like "ee" in see' },
  { letter: 'J', name: 'ji', ipa: '[ʒi]', hint: 'like "zhee" — soft g as in measure' },
  { letter: 'K', name: 'ka', ipa: '[kɑ]', hint: 'like "kah"' },
  { letter: 'L', name: 'elle', ipa: '[ɛl]', hint: 'like "ell" in bell' },
  { letter: 'M', name: 'emme', ipa: '[ɛm]', hint: 'like "emm" in them' },
  { letter: 'N', name: 'enne', ipa: '[ɛn]', hint: 'like "enn" in pen' },
  { letter: 'O', name: 'o', ipa: '[o]', hint: 'like "oh" (no w-glide)' },
  { letter: 'P', name: 'pé', ipa: '[pe]', hint: 'like "pay" (no y-glide)' },
  { letter: 'Q', name: 'qu', ipa: '[ky]', hint: '"k" + French u: say "ee", round your lips' },
  { letter: 'R', name: 'erre', ipa: '[ɛʁ]', hint: '"air" with a throaty gargled r' },
  { letter: 'S', name: 'esse', ipa: '[ɛs]', hint: 'like "ess" in mess' },
  { letter: 'T', name: 'té', ipa: '[te]', hint: 'like "tay" (no y-glide)' },
  { letter: 'U', name: 'u', ipa: '[y]', hint: 'say "ee", round your lips — no English equivalent' },
  { letter: 'V', name: 'vé', ipa: '[ve]', hint: 'like "vay" (no y-glide)' },
  { letter: 'W', name: 'double vé', ipa: '[dubləve]', hint: '"doo-bluh-vay"' },
  { letter: 'X', name: 'ixe', ipa: '[iks]', hint: 'like "eeks"' },
  { letter: 'Y', name: 'i grec', ipa: '[iɡʁɛk]', hint: '"ee-grek" — literally "Greek i"' },
  { letter: 'Z', name: 'zède', ipa: '[zɛd]', hint: 'like "zed"' },
];
